"""cria tabela usuario

Revision ID: 01d1114907f5
Revises: 
Create Date: 2026-09-04 11:18:39.042469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01d1114907f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sexo', sa.Enum('masculino', 'feminino', name='sexo'), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('altura_cm', sa.Float(), nullable=False),
    sa.CheckConstraint('altura_cm > 0 AND altura_cm < 300', name='ck_usuario_altura_valida'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
    # op.drop_table nao derruba o ENUM do Postgres: sem esta linha, o proximo
    # upgrade quebra com DuplicateObject: type "sexo" already exists.
    sa.Enum(name='sexo').drop(op.get_bind(), checkfirst=True)
