"""cria objetivo, registro_diario e macronutrientes

Revision ID: 95daa784a40b
Revises: 01d1114907f5
Create Date: 2026-09-04 11:28:23.541552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95daa784a40b'
down_revision: Union[str, Sequence[str], None] = '01d1114907f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('emagrecer', 'manter', 'ganhar_massa', name='tipo_objetivo'), nullable=False),
    sa.Column('nivel_atividade', sa.Enum('sedentario', 'leve', 'moderado', 'intenso', 'muito_intenso', name='nivel_atividade'), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('peso_meta_kg', sa.Float(), nullable=True),
    sa.Column('tmb_kcal', sa.Float(), nullable=False),
    sa.Column('get_kcal', sa.Float(), nullable=False),
    sa.Column('meta_kcal', sa.Float(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('peso_kg > 0', name='ck_objetivo_peso_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_objetivo_um_ativo_por_usuario', 'objetivo', ['usuario_id'], unique=True, postgresql_where=sa.text('ativo'))
    op.create_index(op.f('ix_objetivo_usuario_id'), 'objetivo', ['usuario_id'], unique=False)
    op.create_table('registro_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('calorias_kcal', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.CheckConstraint('calorias_kcal >= 0', name='ck_registro_calorias_nao_negativas'),
    sa.CheckConstraint('peso_kg > 0', name='ck_registro_peso_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'data', name='uq_registro_diario_usuario_data')
    )
    op.create_index(op.f('ix_registro_diario_usuario_id'), 'registro_diario', ['usuario_id'], unique=False)
    op.create_table('macronutrientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('meta', 'consumo', name='tipo_macro'), nullable=False),
    sa.Column('objetivo_id', sa.Integer(), nullable=True),
    sa.Column('registro_diario_id', sa.Integer(), nullable=True),
    sa.Column('proteina_g', sa.Float(), nullable=False),
    sa.Column('carboidrato_g', sa.Float(), nullable=False),
    sa.Column('gordura_g', sa.Float(), nullable=False),
    sa.CheckConstraint("(tipo = 'meta' AND objetivo_id IS NOT NULL AND registro_diario_id IS NULL) OR (tipo = 'consumo' AND registro_diario_id IS NOT NULL AND objetivo_id IS NULL)", name='ck_macronutrientes_discriminador'),
    sa.CheckConstraint('proteina_g >= 0 AND carboidrato_g >= 0 AND gordura_g >= 0', name='ck_macronutrientes_nao_negativo'),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registro_diario_id'], ['registro_diario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_macro_consumo_unico_por_registro', 'macronutrientes', ['registro_diario_id'], unique=True, postgresql_where=sa.text("tipo = 'consumo'"))
    op.create_index('ix_macro_meta_unica_por_objetivo', 'macronutrientes', ['objetivo_id'], unique=True, postgresql_where=sa.text("tipo = 'meta'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_macro_meta_unica_por_objetivo', table_name='macronutrientes', postgresql_where=sa.text("tipo = 'meta'"))
    op.drop_index('ix_macro_consumo_unico_por_registro', table_name='macronutrientes', postgresql_where=sa.text("tipo = 'consumo'"))
    op.drop_table('macronutrientes')
    op.drop_index(op.f('ix_registro_diario_usuario_id'), table_name='registro_diario')
    op.drop_table('registro_diario')
    op.drop_index(op.f('ix_objetivo_usuario_id'), table_name='objetivo')
    op.drop_index('ix_objetivo_um_ativo_por_usuario', table_name='objetivo', postgresql_where=sa.text('ativo'))
    op.drop_table('objetivo')
    # ### end Alembic commands ###
    # op.drop_table nao derruba os ENUMs do Postgres: sem este loop, o proximo
    # upgrade quebra com DuplicateObject: type "tipo_macro" already exists.
    for nome in ('tipo_macro', 'nivel_atividade', 'tipo_objetivo'):
        sa.Enum(name=nome).drop(op.get_bind(), checkfirst=True)
